language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - stage: production-started
      name: Deployment Started
      script: npx @parameter1/base-cms-newsletter-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=production]

    #############################
    # vvv ADD SERVICES HERE vvv #
    #############################

    - stage: production
      name: For Construction Pros
      script: npx @parameter1/base-cms-newsletter-deployment-tool deploy fcp newsletters
      install: skip
      env: [ENVIRONMENT=production]

    - stage: production
      name: Supply & Demand Chain
      script: npx @parameter1/base-cms-newsletter-deployment-tool deploy sdce newsletters
      install: skip
      env: [ENVIRONMENT=production]

    - stage: production
      name: Green Industry Pros
      script: npx @parameter1/base-cms-newsletter-deployment-tool deploy gip newsletters
      install: skip
      env: [ENVIRONMENT=production]

    - stage: production
      name: Food Logistics
      script: npx @parameter1/base-cms-newsletter-deployment-tool deploy fl newsletters
      install: skip
      env: [ENVIRONMENT=production]

    - stage: production
      name: OEM Off Highway
      script: npx @parameter1/base-cms-newsletter-deployment-tool deploy oem newsletters
      install: skip
      env: [ENVIRONMENT=production]

    #############################
    # ^^^ ADD SERVICES HERE ^^^ #
    #############################

    - stage: production-finished
      name: Deployment Finished
      script: npx @parameter1/base-cms-newsletter-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=production]
